version: 2

orbs:
    android: circleci/android@0.2.1

on: 
  push:
    branches: 
      - dev
      - master
  pull_request:
    branches: 
      - dev

jobs:
  build:
    steps:
        - checkout
        - run:
            name: Run Unit Test
            command: ./gradlew test
        - run:
            name: Run Jacoco Report
            command: ./gradlew jacocoReport
        - run:
            name: Run Jacoco Full Report
            command: ./gradlew jacocoFullReport
        - run:
            name: Run Build
            command: ./gradlew build
