version: 2.1

orbs:
    android: circleci/android@0.2.1
    codecov: codecov/codecov@1.0.2
    

on: 
  push:
    branches: 
      - dev
      - master
  pull_request:
    branches: 
      - dev

jobs:
  build:
    docker:
        - image: circleci/android:api-25
      
    steps:
        - checkout
        - run:
            name: Run Unit Test
            command: ./gradlew test
        - run:
            name: Run Jacoco Report
            command: ./gradlew jacocoReport
        - run:
            name: Run Jacoco Full Report
            command: ./gradlew jacocoFullReport
        - run:
            name: Run Build
            command: ./gradlew build
        - codecov/upload:
            file: ./sample/build/reports/jacoco/coverage.xml
